spring.application.name=cartverse-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cartverse
spring.datasource.username=postgres
spring.datasource.password=arun123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true